
ALTER PROCEDURE [QATALUM].[P_SYNERGI_POST_TEMP_SAVE] @nTrans INT
AS
BEGIN

   exec QATALUM.P_ACTION_EMAILS @nTrans

   DELETE FROM QATALUM.D_ACTION_REFERENCE WHERE TRANS = @nTrans AND REFERENCE =56
   UPDATE QATALUM.D_TRANS SET PERSON_IN_CHARGE = PERSON_EXT_1  WHERE TRANS = @nTrans AND PERSON_EXT_1  > 0 AND APPLICATION IN (20,21)
END
GO
PRINT N'Creating Procedure [QATALUM].[P_MERGE_ACTION_REFERENCE]...';


GO





CREATE   OR ALTER    PROCEDURE [QATALUM].[P_MERGE_ACTION_REFERENCE]
     @TRANS INT
	 ,@ACTION_NO int
    ,@REFERENCE INT 
    ,@INT_VALUE bigint  = 0
    ,@FLOAT_VALUE FLOAT  = 0
    ,@STRING_VALUE nvarchar(2000) = ''
	,@DATE_VALUE DATETIME = NULL
    ,@REFERENCE_OPTION INT  = 0

AS
BEGIN 


   DECLARE @REFERENCE_TYPE INT
   DECLARE @NEXT_REFERENCE_NO INT
   IF @DATE_VALUE IS NULL
   BEGIN
     SET @DATE_VALUE = GETDATE()
   END 

   SELECT  @REFERENCE_TYPE = REFERENCE_TYPE FROM QATALUM.C_REFERENCE  WITH (NOLOCK) WHERE REFERENCE = @REFERENCE

   SELECT @NEXT_REFERENCE_NO = ISNULL( MAX(REFERENCE_NO),0) +1 FROM QATALUM.D_ACTION_REFERENCE   WITH(NOLOCK) WHERE TRANS = @TRANS AND ACTION_NO=@ACTION_NO

   --TEXT
   IF ( @REFERENCE_TYPE = 1 )
     BEGIN
        IF EXISTS(select 1 from QATALUM.D_ACTION_REFERENCE  WITH (NOLOCK) WHERE REFERENCE = @REFERENCE AND TRANS=@TRANS AND ACTION_NO=@ACTION_NO )  
            BEGIN
              UPDATE QATALUM.D_ACTION_REFERENCE SET VALUE = @STRING_VALUE
              WHERE  REFERENCE = @REFERENCE AND TRANS=@TRANS AND ACTION_NO=@ACTION_NO 
            END
        ELSE  
            BEGIN                   
                INSERT INTO QATALUM.D_ACTION_REFERENCE (TRANS,REFERENCE_NO,REFERENCE, VALUE, REFERENCE_OPTION, ACTION_NO)
                VALUES(@TRANS,@NEXT_REFERENCE_NO,   @REFERENCE,@STRING_VALUE,0,@ACTION_NO)
            END   
     END
    -- DATE
   ELSE IF ( @REFERENCE_TYPE = 6 OR  @REFERENCE_TYPE = 10 )
     BEGIN
        IF EXISTS(select 1 from QATALUM.D_ACTION_REFERENCE  WITH (NOLOCK) WHERE REFERENCE = @REFERENCE AND TRANS=@TRANS AND ACTION_NO=@ACTION_NO )  
            BEGIN
              UPDATE QATALUM.D_ACTION_REFERENCE SET VALUE_DATE = @DATE_VALUE
              WHERE  REFERENCE = @REFERENCE AND TRANS=@TRANS AND ACTION_NO=@ACTION_NO 
            END
        ELSE  
            BEGIN                   
                INSERT INTO QATALUM.D_ACTION_REFERENCE (TRANS,REFERENCE_NO,REFERENCE, VALUE_DATE, REFERENCE_OPTION,ACTION_NO)
                VALUES(@TRANS,@NEXT_REFERENCE_NO,   @REFERENCE,@DATE_VALUE,0,@ACTION_NO)
            END   
     END
     -- FLOAT
    ELSE IF ( @REFERENCE_TYPE = 8  OR @FLOAT_VALUE > 0)
     BEGIN
        IF EXISTS(select 1 from QATALUM.D_ACTION_REFERENCE  WITH (NOLOCK) WHERE REFERENCE = @REFERENCE AND TRANS=@TRANS AND ACTION_NO=@ACTION_NO)  
            BEGIN
              UPDATE QATALUM.D_ACTION_REFERENCE SET VALUE_FLOAT = @FLOAT_VALUE
              WHERE  REFERENCE = @REFERENCE AND TRANS=@TRANS AND ACTION_NO=@ACTION_NO
            END
        ELSE  
            BEGIN                   
                INSERT INTO QATALUM.D_ACTION_REFERENCE (TRANS,REFERENCE_NO,REFERENCE, VALUE_FLOAT, REFERENCE_OPTION,ACTION_NO)
                VALUES(@TRANS,@NEXT_REFERENCE_NO,   @REFERENCE,@FLOAT_VALUE,0,@ACTION_NO)
            END   
     END  
     -- INT
    ELSE IF ( @REFERENCE_TYPE = 7 )
     BEGIN
        IF EXISTS(select 1 from QATALUM.D_ACTION_REFERENCE WITH (NOLOCK)  WHERE REFERENCE = @REFERENCE AND TRANS=@TRANS AND ACTION_NO=@ACTION_NO)  
            BEGIN
              UPDATE QATALUM.D_ACTION_REFERENCE SET VALUE_INTEGER = @INT_VALUE
              WHERE  REFERENCE = @REFERENCE AND TRANS=@TRANS AND ACTION_NO=@ACTION_NO
            END
        ELSE  
            BEGIN                   
                INSERT INTO QATALUM.D_ACTION_REFERENCE (TRANS,REFERENCE_NO,REFERENCE, VALUE_INTEGER, REFERENCE_OPTION,ACTION_NO)
                VALUES(@TRANS,@NEXT_REFERENCE_NO,   @REFERENCE,@INT_VALUE,0,@ACTION_NO)
            END   
     END  
     --  SINGLE SELECTION,  MULTI SELECTION
    ELSE IF ( @REFERENCE_TYPE = 4 OR @REFERENCE_TYPE = 5 OR @REFERENCE_TYPE = 9) AND @REFERENCE_OPTION IS NOT NULL
     BEGIN

        IF EXISTS(select 1 from QATALUM.D_ACTION_REFERENCE  WITH (NOLOCK) WHERE REFERENCE = @REFERENCE AND TRANS=@TRANS AND ACTION_NO=@ACTION_NO)  
            BEGIN
              UPDATE QATALUM.D_ACTION_REFERENCE SET REFERENCE_OPTION = @REFERENCE_OPTION
              WHERE  REFERENCE = @REFERENCE AND TRANS=@TRANS AND ACTION_NO=@ACTION_NO
            END
        ELSE  
            BEGIN                   
                INSERT INTO QATALUM.D_ACTION_REFERENCE (TRANS,REFERENCE_NO,REFERENCE,  REFERENCE_OPTION, ACTION_NO)
                VALUES(@TRANS,@NEXT_REFERENCE_NO,   @REFERENCE,@REFERENCE_OPTION,@ACTION_NO)
            END  
     END  
    

END
GO
PRINT N'Creating Procedure [QATALUM].[P_ACTION_POST_SAVE]...';


GO


--EXEC  QATALUM.P_ACTION_POST_SAVE @nTrans=1666994



CREATE OR ALTER  PROCEDURE [QATALUM].[P_ACTION_POST_SAVE]
    @nTrans INT
AS
BEGIN
    
    DECLARE @VALID_TRANS INT = 0, @nPerson_NAME NVARCHAR(1000) = N'', @TRANS_ID int =0, @MAIL_ADDRESS NVARCHAR(max)

    SELECT TOP 1 @TRANS_ID = TRANS_ID FROM QATALUM.D_TRANS WHERE TRANS = @nTrans
    SELECT TOP 1 @nPerson_NAME = LOCKED_BY FROM QATALUM.D_TRANS_INVALID WHERE TRANS = @nTrans

    DECLARE @ACTION_NO INT,
            @DATE_VALUE DATETIME,
            @CHANGE_CNT INT,
            @JUSTIFICATION NVARCHAR(4000),
            @JUSTIFICATION_LOG NVARCHAR(4000),
            @OLD_DATE_VALUE DATETIME,
            @REFERENCE_NO INT;

    SELECT TOP 1 @VALID_TRANS = TRANS_VALID    FROM QATALUM.D_TRANS_INVALID    WHERE TRANS = @nTrans;

    SET @nPerson_NAME = ISNULL(@nPerson_NAME, N'');

    DECLARE CUR_ACTION CURSOR LOCAL FAST_FORWARD FOR
        SELECT ACTION_NO, ACTION_TIME_LIMIT
        FROM
        (
            SELECT ACTION_NO, ACTION_TIME_LIMIT
            FROM QATALUM.D_ACTION
            WHERE TRANS = @nTrans
            EXCEPT
            SELECT ACTION_NO, ACTION_TIME_LIMIT
            FROM QATALUM.D_ACTION
            WHERE TRANS = @VALID_TRANS
        ) K1
        WHERE EXISTS(SELECT 1 FROM  QATALUM.D_ACTION B1 WHERE B1.ACTION_NO = K1.ACTION_NO AND B1.TRANS =@VALID_TRANS);

    OPEN CUR_ACTION;

    FETCH NEXT FROM CUR_ACTION INTO @ACTION_NO, @DATE_VALUE;

    WHILE @@FETCH_STATUS = 0
    BEGIN
       SET @OLD_DATE_VALUE = NULL
       SET @JUSTIFICATION = NULL
       SET @MAIL_ADDRESS = NULL
       SET @CHANGE_CNT = 0
        SELECT TOP 1 @JUSTIFICATION = ISNULL(VALUE, N'')  FROM QATALUM.D_ACTION_REFERENCE  WHERE TRANS = @nTrans  AND ACTION_NO = @ACTION_NO  AND REFERENCE = 53;
        SELECT TOP 1 @JUSTIFICATION_LOG = ISNULL(VALUE, N'')  FROM QATALUM.D_ACTION_REFERENCE  WHERE TRANS = @nTrans  AND ACTION_NO = @ACTION_NO  AND REFERENCE = 54;
        SELECT TOP 1 @CHANGE_CNT = ISNULL(VALUE_INTEGER, 0)  FROM QATALUM.D_ACTION_REFERENCE WHERE TRANS = @nTrans  AND ACTION_NO = @ACTION_NO   AND REFERENCE = 52;

        IF EXISTS(SELECT 1 FROM QATALUM.D_TRANS WHERE TRANS = @nTrans AND PERSON_IN_CHARGE >0)
        BEGIN
            SELECT TOP 1 @MAIL_ADDRESS = P1.EMAIL_ADDRESS
            FROM QATALUM.D_TRANS A1
              INNER JOIN QATALUM.P_PERSON P1
                 ON A1.PERSON_IN_CHARGE = P1.PERSON
            WHERE A1.TRANS =@nTrans    
        END
        ELSE
        BEGIN
            SELECT @MAIL_ADDRESS = STRING_AGG(CAST(P1.EMAIL_ADDRESS AS NVARCHAR(MAX)), N';')
            FROM QATALUM.D_TRANS A1
            --  INNER JOIN QATALUM.A_UNIT aunit
            --    on aunit.DESCEND_UNIT = A1.UNIT_IN_CHARGE
              INNER JOIN QATALUM.P_PERSON P1
                 ON A1.UNIT_IN_CHARGE = P1.MY_UNIT
            WHERE A1.TRANS =@nTrans
    
        END


        --SELECT TOP 1  @OLD_DATE_VALUE = VALUE_DATE FROM QATALUM.D_ACTION_REFERENCE  WHERE TRANS = @nTrans AND ACTION_NO = @ACTION_NO  AND REFERENCE = 51;
        --IF @OLD_DATE_VALUE IS NULL
        SELECT TOP 1 @OLD_DATE_VALUE = ACTION_TIME_LIMIT FROM  QATALUM.D_ACTION WHERE TRANS = @VALID_TRANS AND ACTION_NO = @ACTION_NO
        SET @CHANGE_CNT = ISNULL(@CHANGE_CNT, 0) + 1;

        IF @JUSTIFICATION_LOG IS NULL OR @JUSTIFICATION_LOG = N''
        BEGIN
           SET @JUSTIFICATION_LOG = @nPerson_NAME + N' - ' +  ISNULL(FORMAT((@OLD_DATE_VALUE), 'ddd, MMM dd, yyyy', 'en-US'),N'') + N' - ' + ISNULL(@JUSTIFICATION, N'');
        END
        ELSE
        BEGIN
           SET @JUSTIFICATION_LOG = @JUSTIFICATION_LOG +char(13)+char(10) +@nPerson_NAME + N' - ' +  ISNULL(FORMAT((@OLD_DATE_VALUE), 'ddd, MMM dd, yyyy', 'en-US'),N'') + N' - ' + ISNULL(@JUSTIFICATION, N'');
        END
        
        /* REFERENCE 51 : Original Deadline */
        EXEC QATALUM.P_MERGE_ACTION_REFERENCE @TRANS =@nTrans, @ACTION_NO =@ACTION_NO, @REFERENCE= 51, @DATE_VALUE =@OLD_DATE_VALUE
        /* REFERENCE 52 : Number of times changed */
        EXEC QATALUM.P_MERGE_ACTION_REFERENCE @TRANS =@nTrans, @ACTION_NO =@ACTION_NO, @REFERENCE= 52, @INT_VALUE =@CHANGE_CNT
        /* REFERENCE 54 : Justification Log */
        EXEC QATALUM.P_MERGE_ACTION_REFERENCE @TRANS =@nTrans, @ACTION_NO =@ACTION_NO, @REFERENCE= 54, @STRING_VALUE =@JUSTIFICATION_LOG

        EXEC QATALUM.P_MERGE_ACTION_REFERENCE @TRANS =@nTrans, @ACTION_NO =@ACTION_NO, @REFERENCE= 56, @STRING_VALUE =@JUSTIFICATION
        


        IF ISNULL(@MAIL_ADDRESS ,N'') != N''
        BEGIN
 		    /* Find customer text for mail Message */
            DECLARE @mailMessage NVARCHAR(4000) = ''
		    BEGIN

			    SELECT @mailMessage = DESCRIPTION 
				    FROM QATALUM.X_TEXT 
				    WHERE TEXT = 1317 
				    AND DOMAIN_BLOB = 10 
				    AND LANGUAGE = 2

			    IF @@ROWCOUNT = 0 SELECT @mailMessage = 'Synergi Life case no. <TRANS_ID>, action no. <ACTION_NO> Action Deadline has been changed'
		    END
		    -- Set mail Message
		    SELECT @mailMessage = REPLACE (@mailMessage,'<TRANS_ID>' ,CONVERT(varchar(10), @TRANS_ID))
		    SELECT @mailMessage = REPLACE (@mailMessage,'<ACTION_NO>',CONVERT(varchar(10), @ACTION_NO))

            PRINT(N'SEND EMAIL TO ' + @MAIL_ADDRESS)

            insert into  QATALUM.D_TRANS_TMP_MAIL (TRANS, TMP_MAIL_NO, RECEIVERS_TO, CASE_COMMENT) 
                     values(@nTrans,1,@MAIL_ADDRESS, @mailMessage)
            /*
		    UPDATE QATALUM.D_ACTION
			    SET TMP_MAIL_RECEIVERS_TO = @MAIL_ADDRESS
			    , TMP_MAIL_COMMENT = @mailMessage
		    WHERE QATALUM.D_ACTION.TRANS = @nTrans
			    AND QATALUM.D_ACTION.ACTION_NO = @ACTION_NO; 
                */
        END
      

        UPDATE QATALUM.D_ACTION_REFERENCE   SET VALUE = NULL  WHERE TRANS = @nTrans  AND ACTION_NO = @ACTION_NO  AND REFERENCE = 53;

        FETCH NEXT FROM CUR_ACTION INTO @ACTION_NO, @DATE_VALUE;
    END

    CLOSE CUR_ACTION;
    DEALLOCATE CUR_ACTION;

    
  
    
END
GO
PRINT N'Creating Permission Permission...';


GO
GRANT EXECUTE ON [QATALUM].[P_ACTION_POST_SAVE] TO ROLE_SYNERGI_CORE_APP_SERVICES;


GO
PRINT N'Update complete.';


GO
