delete from qatalum.X_DOMAIN_CONSTRAINTS where  DOMAIN=8875 and  APPLICATION=4 and  OPERATION=11 and  CONSTRAINT_TYPE=23 and  CRITERIA=50034 and  IMPORT_CONSTRAINT_SET=0
insert into qatalum.X_DOMAIN_CONSTRAINTS (DOMAIN,APPLICATION,OPERATION,CONSTRAINT_TYPE,CRITERIA,FLG_ACTIVE,SEQUENCE,DOMAIN_BLOB,TEXT,IMPORT_CONSTRAINT_SET,CRITERIA_RESPONSE_TYPE,FLG_REQUIRED_FIELD ) values ( 8875,20,11,23,50034,1,1,3,5949,0,1,1 ) 
insert into qatalum.X_DOMAIN_CONSTRAINTS (DOMAIN,APPLICATION,OPERATION,CONSTRAINT_TYPE,CRITERIA,FLG_ACTIVE,SEQUENCE,DOMAIN_BLOB,TEXT,IMPORT_CONSTRAINT_SET,CRITERIA_RESPONSE_TYPE,FLG_REQUIRED_FIELD ) values ( 8875,21,11,23,50034,1,1,3,5949,0,1,1 ) 

insert into qatalum.X_CRITERIA (CRITERIA,CRITERIA_SQL,CRITERIA_TYPE,SQL_BUILD ) values ( 50035,N'D_ACTION.ACTION_STATUS IN (0, 1, 2)',12,3 ) 
insert into qatalum.L_CRITERIA (CRITERIA,LANGUAGE,DESCRIPTION,LONG_DESCRIPTION ) values ( 50035,2,N'Confirmation of implementation or cancellation - Hide',NULL ) 


update qatalum.X_DOMAIN_APPL set USE_HIDE_CRITERIA =2 , HIDE_CRITERIA =50035 where domain = 50100 and application =4