


GO
PRINT N'Creating Table [synergix].[C_ROLE_EXT]...';


GO
CREATE TABLE [synergix].[C_ROLE_EXT] (
    [ROLE_EXT] INT      NOT NULL,
    [DISABLED] DATETIME NULL,
    [SEQUENCE] INT      NULL,
    CONSTRAINT [XPKC_ROLE_EXT] PRIMARY KEY CLUSTERED ([ROLE_EXT] ASC)
);


GO
PRINT N'Creating Table [synergix].[C_YESNO_EXT]...';


GO
CREATE TABLE [synergix].[C_YESNO_EXT] (
    [YESNO_EXT] INT      NOT NULL,
    [DISABLED]  DATETIME NULL,
    [SEQUENCE]  INT      NULL,
    CONSTRAINT [XPKC_YESNO_EXT] PRIMARY KEY CLUSTERED ([YESNO_EXT] ASC)
);


GO
PRINT N'Creating Table [synergix].[E_ROLE_EXT]...';


GO
CREATE TABLE [synergix].[E_ROLE_EXT] (
    [ROLE_EXT]   INT            NOT NULL,
    [EXPORT_SET] INT            NOT NULL,
    [EXPORT_NO]  INT            NOT NULL,
    [EXPORT]     NVARCHAR (254) NOT NULL,
    CONSTRAINT [XPKE_ROLE_EXT] PRIMARY KEY CLUSTERED ([ROLE_EXT] ASC, [EXPORT_SET] ASC, [EXPORT_NO] ASC)
);


GO
PRINT N'Creating Table [synergix].[E_YESNO_EXT]...';


GO
CREATE TABLE [synergix].[E_YESNO_EXT] (
    [YESNO_EXT]  INT            NOT NULL,
    [EXPORT_SET] INT            NOT NULL,
    [EXPORT_NO]  INT            NOT NULL,
    [EXPORT]     NVARCHAR (254) NOT NULL,
    CONSTRAINT [XPKE_YESNO_EXT] PRIMARY KEY CLUSTERED ([YESNO_EXT] ASC, [EXPORT_SET] ASC, [EXPORT_NO] ASC)
);


GO
PRINT N'Creating Table [synergix].[L_ROLE_EXT]...';


GO
CREATE TABLE [synergix].[L_ROLE_EXT] (
    [ROLE_EXT]    INT            NOT NULL,
    [LANGUAGE]    INT            NOT NULL,
    [DESCRIPTION] NVARCHAR (254) NOT NULL,
    CONSTRAINT [XPKL_ROLE_EXT] PRIMARY KEY CLUSTERED ([ROLE_EXT] ASC, [LANGUAGE] ASC)
);


GO
PRINT N'Creating Table [synergix].[L_YESNO_EXT]...';


GO
CREATE TABLE [synergix].[L_YESNO_EXT] (
    [YESNO_EXT]   INT            NOT NULL,
    [LANGUAGE]    INT            NOT NULL,
    [DESCRIPTION] NVARCHAR (254) NOT NULL,
    CONSTRAINT [XPKL_YESNO_EXT] PRIMARY KEY CLUSTERED ([YESNO_EXT] ASC, [LANGUAGE] ASC)
);


GO
PRINT N'Creating Foreign Key [synergix].[R_ROLE_EXT_1719]...';


GO
ALTER TABLE [synergix].[E_ROLE_EXT] WITH NOCHECK
    ADD CONSTRAINT [R_ROLE_EXT_1719] FOREIGN KEY ([ROLE_EXT]) REFERENCES [synergix].[C_ROLE_EXT] ([ROLE_EXT]);


GO
PRINT N'Creating Foreign Key [synergix].[R_ROLE_EXT_1731]...';


GO
ALTER TABLE [synergix].[E_ROLE_EXT] WITH NOCHECK
    ADD CONSTRAINT [R_ROLE_EXT_1731] FOREIGN KEY ([EXPORT_SET]) REFERENCES [synergix].[C_EXPORT_SET] ([EXPORT_SET]);


GO
PRINT N'Creating Foreign Key [synergix].[R_YESNO_EXT_1719]...';


GO
ALTER TABLE [synergix].[E_YESNO_EXT] WITH NOCHECK
    ADD CONSTRAINT [R_YESNO_EXT_1719] FOREIGN KEY ([YESNO_EXT]) REFERENCES [synergix].[C_YESNO_EXT] ([YESNO_EXT]);


GO
PRINT N'Creating Foreign Key [synergix].[R_YESNO_EXT_1731]...';


GO
ALTER TABLE [synergix].[E_YESNO_EXT] WITH NOCHECK
    ADD CONSTRAINT [R_YESNO_EXT_1731] FOREIGN KEY ([EXPORT_SET]) REFERENCES [synergix].[C_EXPORT_SET] ([EXPORT_SET]);


GO
PRINT N'Creating Foreign Key [synergix].[R_ROLE_EXT_1718]...';


GO
ALTER TABLE [synergix].[L_ROLE_EXT] WITH NOCHECK
    ADD CONSTRAINT [R_ROLE_EXT_1718] FOREIGN KEY ([ROLE_EXT]) REFERENCES [synergix].[C_ROLE_EXT] ([ROLE_EXT]);


GO
PRINT N'Creating Foreign Key [synergix].[R_ROLE_EXT_1726]...';


GO
ALTER TABLE [synergix].[L_ROLE_EXT] WITH NOCHECK
    ADD CONSTRAINT [R_ROLE_EXT_1726] FOREIGN KEY ([LANGUAGE]) REFERENCES [synergix].[X_LANGUAGE] ([LANGUAGE]);


GO
PRINT N'Creating Foreign Key [synergix].[R_YESNO_EXT_1718]...';


GO
ALTER TABLE [synergix].[L_YESNO_EXT] WITH NOCHECK
    ADD CONSTRAINT [R_YESNO_EXT_1718] FOREIGN KEY ([YESNO_EXT]) REFERENCES [synergix].[C_YESNO_EXT] ([YESNO_EXT]);


GO
PRINT N'Creating Foreign Key [synergix].[R_YESNO_EXT_1726]...';


GO
ALTER TABLE [synergix].[L_YESNO_EXT] WITH NOCHECK
    ADD CONSTRAINT [R_YESNO_EXT_1726] FOREIGN KEY ([LANGUAGE]) REFERENCES [synergix].[X_LANGUAGE] ([LANGUAGE]);


GO
PRINT N'Creating Function [synergix].[EXIST_SYNERGI_REFERENCE_OPTION]...';


GO


CREATE   function [synergix].[EXIST_SYNERGI_REFERENCE_OPTION](@TRANS INT, @REFERENCE INT, @REFERENCE_OPTION INT) RETURNS INT
AS

BEGIN
   DECLARE @RET INT =0
   SELECT @RET =
      CASE WHEN EXISTS (SELECT 1 FROM SYNERGIX.D_SYNERGI_REFERENCE  WITH(NOLOCK) WHERE TRANS = @TRANS AND REFERENCE = @REFERENCE
              AND REFERENCE_OPTION = @REFERENCE_OPTION) THEN 1
		   ELSE 0
	  END

   return @RET;
END
GO
PRINT N'Creating Function [synergix].[GET_EMAIL_TEXT]...';


GO




CREATE          FUNCTION [synergix].[GET_EMAIL_TEXT] (@PERSON int, @DOMAIN_BLOB int, @TEXT int)
RETURNS NVARCHAR(4000)
AS
BEGIN
      DECLARE @RET_TEXT NVARCHAR(4000), @DEFAULT_LANG int

	  SELECT TOP 1 @DEFAULT_LANG = LANGUAGE FROM SYNERGIX.P_PERSON WITH(NOLOCK) WHERE PERSON =@PERSON
	  SET @DEFAULT_LANG = ISNULL(@DEFAULT_LANG,2)

	  SELECT TOP 1 @RET_TEXT = DESCRIPTION FROM SYNERGIX.X_TEXT WITH(NOLOCK) WHERE DOMAIN_BLOB = @DOMAIN_BLOB AND TEXT =@TEXT AND LANGUAGE= @DEFAULT_LANG
	  
	  RETURN ISNULL(@RET_TEXT,N'')


END
GO
PRINT N'Creating Function [synergix].[GET_VALID_TRANS]...';


GO
create   function [synergix].[GET_VALID_TRANS](@TRANS INT) RETURNS INT
AS
BEGIN
   DECLARE @TRANS_ID int
   DECLARE @RET_TRANS int =0
   SELECT @TRANS_ID = TRANS_ID FROM SYNERGIX.D_TRANS  WITH(NOLOCK) WHERE TRANS = @TRANS

   select  @RET_TRANS= V1.TRANS
   from SYNERGIX.D_TRANS T1 WITH(NOLOCK) 
     INNER JOIN SYNERGIX.D_TRANS_VALID V1 WITH(NOLOCK) 
	   ON T1.TRANS = V1.TRANS
	WHERE T1.TRANS_ID = @TRANS_ID

   RETURN @RET_TRANS
END
GO
PRINT N'Creating Function [synergix].[IS_REFERENCE_CHANGED_DOUBLE]...';


GO




CREATE          FUNCTION [synergix].[IS_REFERENCE_CHANGED_DOUBLE] (@TRANS int, @OPT_REFERENCES int, @INT_REFERENCE int)
RETURNS int
AS
BEGIN

	  IF   EXISTS(SELECT 1 FROM SYNERGIX.D_SYNERGI_REFERENCE R20794 WITH(NOLOCK) 
		                   WHERE R20794.TRANS =@TRANS  
						   AND R20794.REFERENCE = @OPT_REFERENCES
	                       AND  NOT EXISTS(SELECT 1 FROM  SYNERGIX.D_SYNERGI_REFERENCE R20796 WITH(NOLOCK)
						                  WHERE  R20794.TRANS =R20796.TRANS
										  AND  R20796.REFERENCE = @INT_REFERENCE
										  AND  R20794.REFERENCE_OPTION = R20796.VALUE_INTEGER))
	   BEGIN
	      RETURN 1
	   END
	   RETURN 0


END
GO
PRINT N'Creating Procedure [synergix].[EXT_ALL_POST_SAVE]...';


GO
SET ANSI_NULLS ON;

SET QUOTED_IDENTIFIER OFF;


GO


/*
 exec [synergix].[EXT_ALL_POST_SAVE] @nTrans=1898149, @nPerson =0
  select * FROM synergix.D_TRANS_TMP_MAIL


*/


CREATE     PROCEDURE [synergix].[EXT_ALL_POST_SAVE] @nTrans INT , @nPerson int
AS
begin
  PRINT(N'EXT_ALL_POST_SAVE')
  DECLARE @APPLICATION int =0, @QA_VERIFY_EMAIL NVARCHAR(4000),@ENV_VERIFY_EMAIL NVARCHAR(4000), @RECEIVER NVARCHAR(4000), @PIC_EMAIL nvarchar(4000)
          ,@STATUS int =0,@STATUS_TEMP int =0, @VALID_TRANS int =SYNERGIX.GET_VALID_TRANS(@nTrans) --@IS_EMAIL_READY int =0, 

  SELECT TOP 1 @APPLICATION = APPLICATION ,@PIC_EMAIL= P1.EMAIL_ADDRESS,@STATUS = T1.STATUS, @STATUS_TEMP = T1.STATUS_TEMP
  FROM SYNERGIX.D_TRANS  T1 WITH(NOLOCK)
     LEFT OUTER JOIN  SYNERGIX.P_PERSON P1 WITH(NOLOCK) 
       ON T1.PERSON_IN_CHARGE = P1.PERSON
  WHERE TRANS = @nTrans

  --IF EXISTS(SELECT 1 FROM synergix.D_TRANS_TMP_MAIL WHERE TRANS = @nTrans)
  --   SET @IS_EMAIL_READY =1

  IF EXISTS(SELECT 1 FROM SYNERGIX.A_APPLICATION WHERE DESCEND_APPLICATION IN (179,541) AND APPLICATION =@APPLICATION)
     
  -- Enviroment, Cost of Poor Quality
  BEGIN
      select @QA_VERIFY_EMAIL= STRING_AGG(p1.EMAIL_ADDRESS,N', ') 
        from synergix.P_EXTRA_INFO e1 WITH(NOLOCK)
            INNER JOIN SYNERGIX.P_PERSON p1 WITH(NOLOCK)
                on e1.PERSON = p1.PERSON
        WHERE e1.EXTRA_INFO = 1
        AND   e1.VALUE_CODE =1
        and   p1.EMAIL_ADDRESS  IS NOT NULL

        select @ENV_VERIFY_EMAIL= STRING_AGG(p1.EMAIL_ADDRESS,N', ') 
        from synergix.P_EXTRA_INFO e1 WITH(NOLOCK)
            INNER JOIN SYNERGIX.P_PERSON p1 WITH(NOLOCK)
                on e1.PERSON = p1.PERSON
        WHERE e1.EXTRA_INFO = 2
        AND   e1.VALUE_CODE =1
        and   p1.EMAIL_ADDRESS  IS NOT NULL
        SET @RECEIVER = (CASE WHEN @APPLICATION = 541 THEN @QA_VERIFY_EMAIL
                            ELSE @ENV_VERIFY_EMAIL END)    
        IF @STATUS =1  
        BEGIN
             IF SYNERGIX.EXIST_SYNERGI_REFERENCE_OPTION(@nTrans,210,1) = 1 AND SYNERGIX.EXIST_SYNERGI_REFERENCE_OPTION(@VALID_TRANS,210,1) = 0
               BEGIN   
                  PRINT(N'send verification email start')
                  insert into  synergix.D_TRANS_TMP_MAIL (TRANS, TMP_MAIL_NO, RECEIVERS_TO, CASE_COMMENT) 
                     values(@nTrans,1,@RECEIVER, SYNERGIX.GET_EMAIL_TEXT(@nPerson, 10, 8103))
                  --EXEC SYNERGIX.EXT_MERGE_SYNERGI_REFERENCE @TRANS =@nTrans, @REFERENCE =212, @INT_VALUE=1
                  PRINT(N'send verification email end')
               END
      
             DECLARE @R211 int =0, @R211_BEFORE int =0

             SELECT TOP 1 @R211= REFERENCE_OPTION FROM SYNERGIX.D_SYNERGI_REFERENCE WITH(NOLOCK) WHERE TRANS =@nTrans AND REFERENCE =211
             SELECT TOP 1 @R211_BEFORE= REFERENCE_OPTION FROM SYNERGIX.D_SYNERGI_REFERENCE WITH(NOLOCK) WHERE TRANS =@VALID_TRANS AND REFERENCE =211
             PRINT(STR(@R211_BEFORE) + N'--->'+ STR(@R211))
             IF ISNULL(@R211,0) = 232 AND ISNULL(@R211,0) != ISNULL(@R211_BEFORE,0) 
             BEGIN
                  PRINT(N'send verification result : approve start')
                  insert into  synergix.D_TRANS_TMP_MAIL (TRANS, TMP_MAIL_NO, RECEIVERS_TO, CASE_COMMENT) 
                     values(@nTrans,1,@PIC_EMAIL, SYNERGIX.GET_EMAIL_TEXT(@nPerson, 10, 8104))
                --  EXEC SYNERGIX.EXT_MERGE_SYNERGI_REFERENCE @TRANS =@nTrans, @REFERENCE =213, @INT_VALUE=1
                  PRINT(N'send verification result : approve end')
             END
             IF ISNULL(@R211,0) = 233 AND ISNULL(@R211,0) != ISNULL(@R211_BEFORE,0) 
             BEGIN
                  PRINT(N'send verification result : reject start')
                  insert into  synergix.D_TRANS_TMP_MAIL (TRANS, TMP_MAIL_NO, RECEIVERS_TO, CASE_COMMENT) 
                     values(@nTrans,1,@PIC_EMAIL, SYNERGIX.GET_EMAIL_TEXT(@nPerson, 10, 8105))
                 -- EXEC SYNERGIX.EXT_MERGE_SYNERGI_REFERENCE @TRANS =@nTrans, @REFERENCE =213, @INT_VALUE=2
                  PRINT(N'send verification result : reject end')
             END
       END
       
        IF @STATUS_TEMP = 3 AND @STATUS_TEMP != @STATUS
        BEGIN
            PRINT(N'Status In Progress start')
            DECLARE @ACT_MAIL NVARCHAR(4000) = N'', @FINAL_MAIL NVARCHAR(4000) =N''

            SELECT @ACT_MAIL= STRING_AGG(p1.EMAIL_ADDRESS,N', ') 
            FROM SYNERGIX.D_ACTION A1 WITH(NOLOCK)
                INNER JOIN SYNERGIX.P_PERSON P1 WITH(NOLOCK)
                ON A1.PERSON_IN_CHARGE = P1.PERSON
            WHERE A1.TRANS =@nTrans
            AND   P1.EMAIL_ADDRESS IS NOT NULL

            SET @FINAL_MAIL = @PIC_EMAIL 
            IF  ISNULL(@ACT_MAIL,N'') != N''
                SET @FINAL_MAIL = @FINAL_MAIL + N',' +  @ACT_MAIL

            insert into  synergix.D_TRANS_TMP_MAIL (TRANS, TMP_MAIL_NO, RECEIVERS_TO, CASE_COMMENT) 
                values(@nTrans,1,@FINAL_MAIL, SYNERGIX.GET_EMAIL_TEXT(@nPerson, 10, 8108))
                 
            PRINT(N'Status In Progress end')
        END
        IF @STATUS_TEMP = 4 AND @STATUS_TEMP != @STATUS
        BEGIN
            PRINT(N'Status  Approved start')
            insert into  synergix.D_TRANS_TMP_MAIL (TRANS, TMP_MAIL_NO, RECEIVERS_TO, CASE_COMMENT) 
                values(@nTrans,1,@PIC_EMAIL, SYNERGIX.GET_EMAIL_TEXT(@nPerson, 10, 8109))                 
            PRINT(N'Status  Approved end')
        END

        IF @STATUS_TEMP = 6 AND @STATUS_TEMP != @STATUS
        BEGIN
            PRINT(N'Status  Closed start')
            DECLARE @CLOSE_MAIL nvarchar(4000)
            SELECT TOP 1 @CLOSE_MAIL= EMAIL_ADDRESS FROM SYNERGIX.P_PERSON P1 WITH(NOLOCK) 
               where PERSON IN (SELECT VALUE_INTEGER FROM SYNERGIX.D_SYNERGI_REFERENCE WITH(NOLOCK) WHERE TRANS =@nTrans AND REFERENCE =214 )

            IF ISNULL(@CLOSE_MAIL,N'') != N''
            BEGIN
              insert into  synergix.D_TRANS_TMP_MAIL (TRANS, TMP_MAIL_NO, RECEIVERS_TO, CASE_COMMENT) 
                values(@nTrans,1,@PIC_EMAIL, SYNERGIX.GET_EMAIL_TEXT(@nPerson, 10, 8110)) 
            END
                            
            PRINT(N'Status  Closed end')
        END


      IF @STATUS IN (0,1,7)  
      BEGIN
          IF SYNERGIX.EXIST_SYNERGI_REFERENCE_OPTION(@nTrans,211,233) = 1
          BEGIN
             DELETE FROM SYNERGIX.D_SYNERGI_REFERENCE WHERE TRANS =@nTrans AND REFERENCE  IN (210,211)
          END
      END
     
  END




  
  ---------------------------------------------
end
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Creating Procedure [synergix].[EXT_MERGE_SYNERGI_REFERENCE]...';


GO

CREATE   PROCEDURE [synergix].[EXT_MERGE_SYNERGI_REFERENCE]
     @TRANS INT
    ,@REFERENCE INT 
    ,@INT_VALUE BIGINT  = 0
    ,@FLOAT_VALUE FLOAT  = 0
    ,@STRING_VALUE NVARCHAR(2000) = N''
    ,@DATE_VALUE DATETIME = NULL
    ,@REFERENCE_OPTION INT  = 0
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM SYNERGIX.D_TRANS WITH (NOLOCK) WHERE TRANS = @TRANS)
        RETURN;

    IF @DATE_VALUE IS NULL SET @DATE_VALUE = GETDATE();

    DECLARE @REFERENCE_TYPE INT;

    SELECT @REFERENCE_TYPE = REFERENCE_TYPE
    FROM SYNERGIX.C_REFERENCE WITH (NOLOCK)
    WHERE REFERENCE = @REFERENCE;

    IF @REFERENCE_TYPE = 8 AND @FLOAT_VALUE = 0 AND @STRING_VALUE <> N''
        SET @FLOAT_VALUE = TRY_CAST(@STRING_VALUE AS FLOAT);

    IF @REFERENCE_TYPE = 7 AND @INT_VALUE = 0 AND @STRING_VALUE <> N''
        SET @INT_VALUE = TRY_CAST(@STRING_VALUE AS BIGINT);

    -- 1) UPDATE 먼저
    UPDATE t
       SET VALUE           = CASE WHEN @REFERENCE_TYPE = 1 THEN @STRING_VALUE ELSE t.VALUE END,
           VALUE_DATE      = CASE WHEN @REFERENCE_TYPE IN (6,10) THEN @DATE_VALUE ELSE t.VALUE_DATE END,
           VALUE_FLOAT     = CASE WHEN @REFERENCE_TYPE = 8 THEN @FLOAT_VALUE ELSE t.VALUE_FLOAT END,
           VALUE_INTEGER   = CASE WHEN @REFERENCE_TYPE = 7 THEN @INT_VALUE ELSE t.VALUE_INTEGER END,
           REFERENCE_OPTION= CASE WHEN @REFERENCE_TYPE IN (4,5,9) THEN @REFERENCE_OPTION ELSE t.REFERENCE_OPTION END
    FROM SYNERGIX.D_SYNERGI_REFERENCE t
    WHERE t.TRANS = @TRANS
      AND t.REFERENCE = @REFERENCE;

    IF @@ROWCOUNT > 0
        RETURN;

    -- 2) 없으면 INSERT 시도 (경쟁 대비 TRY/CATCH)
    DECLARE @refno INT;

    BEGIN TRY
        SELECT @refno = ISNULL(MAX(REFERENCE_NO), 0) + 1
        FROM SYNERGIX.D_SYNERGI_REFERENCE WITH (UPDLOCK, HOLDLOCK)
        WHERE TRANS = @TRANS;

        INSERT INTO SYNERGIX.D_SYNERGI_REFERENCE
            (TRANS, REFERENCE_NO, REFERENCE, VALUE, VALUE_DATE, VALUE_FLOAT, VALUE_INTEGER, REFERENCE_OPTION)
        VALUES
            (@TRANS, @refno, @REFERENCE,
             CASE WHEN @REFERENCE_TYPE = 1 THEN @STRING_VALUE ELSE NULL END,
             CASE WHEN @REFERENCE_TYPE IN (6,10) THEN @DATE_VALUE ELSE NULL END,
             CASE WHEN @REFERENCE_TYPE = 8 THEN @FLOAT_VALUE ELSE NULL END,
             CASE WHEN @REFERENCE_TYPE = 7 THEN @INT_VALUE ELSE NULL END,
             CASE WHEN @REFERENCE_TYPE IN (4,5,9) THEN @REFERENCE_OPTION ELSE 0 END);
    END TRY
    BEGIN CATCH
        PRINT('INSERT ERROR  OF D_SYNERGI_REFERENCE')
    END CATCH
END
GO
PRINT N'Creating Procedure [synergix].[EXT_ALL_INIT_SAVE]...';


GO
SET ANSI_NULLS ON;

SET QUOTED_IDENTIFIER OFF;


GO



CREATE     PROCEDURE [synergix].[EXT_ALL_INIT_SAVE] @nTrans INT , @nPerson int
AS
begin
  PRINT(N'EXT_ALL_INIT_SAVE')  
  -- UPDATE SYNERIX.D_TRANS SET   CREATOR_EXT = @nPerson WHERE TRANS =@nTrans AND CREATOR_EXT =0
  EXEC SYNERGIX.EXT_MERGE_SYNERGI_REFERENCE @TRANS =@nTrans, @REFERENCE =214, @INT_VALUE=@nPerson
  ---------------------------------------------
end
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Creating Procedure [synergix].[EXT_ALL_TEMP_SAVE]...';


GO
SET ANSI_NULLS ON;

SET QUOTED_IDENTIFIER OFF;


GO



 -- exec [synergix].[EXT_ALL_TEMP_SAVE] @nTrans=1898120, @nPerson=0

 -- select * FROM synergix.D_TRANS_TMP_MAIL

  -- select SYNERGIX.EXIST_SYNERGI_REFERENCE_OPTION(1898117,210,1)
  -- select SYNERGIX.IS_REFERENCE_CHANGED_DOUBLE(1898117,210,212)

CREATE     PROCEDURE [synergix].[EXT_ALL_TEMP_SAVE] @nTrans INT , @nPerson int
AS
begin
  PRINT(N'EXT_ALL_TEMP_SAVE')

  DECLARE @APPLICATION int =0
          ,@STATUS int =0

  SELECT TOP 1 @APPLICATION = APPLICATION ,@STATUS = T1.STATUS FROM SYNERGIX.D_TRANS  T1 WITH(NOLOCK) WHERE TRANS = @nTrans


   PRINT(N'Target Application '  +STR(@APPLICATION))
  IF EXISTS(SELECT 1 FROM SYNERGIX.A_APPLICATION WHERE DESCEND_APPLICATION IN (179,541) AND APPLICATION =@APPLICATION)
  BEGIN

      IF @STATUS IN (0,1,7)  
      BEGIN
          IF SYNERGIX.EXIST_SYNERGI_REFERENCE_OPTION(@nTrans,210,1) = 1 AND SYNERGIX.IS_REFERENCE_CHANGED_DOUBLE(@nTrans,210,212) = 1
          BEGIN
              DELETE FROM SYNERGIX.D_SYNERGI_REFERENCE WHERE TRANS =@nTrans AND REFERENCE =211
              EXEC SYNERGIX.EXT_MERGE_SYNERGI_REFERENCE @TRANS =@nTrans, @REFERENCE =212, @INT_VALUE=1
          END

          IF SYNERGIX.EXIST_SYNERGI_REFERENCE_OPTION(@nTrans,210,1) = 0
          BEGIN
             DELETE FROM SYNERGIX.D_SYNERGI_REFERENCE WHERE TRANS =@nTrans AND REFERENCE =211
          END
      END
     



  END








 

end
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Checking existing data against newly created constraints';




GO
ALTER TABLE [synergix].[E_ROLE_EXT] WITH CHECK CHECK CONSTRAINT [R_ROLE_EXT_1719];

ALTER TABLE [synergix].[E_ROLE_EXT] WITH CHECK CHECK CONSTRAINT [R_ROLE_EXT_1731];

ALTER TABLE [synergix].[E_YESNO_EXT] WITH CHECK CHECK CONSTRAINT [R_YESNO_EXT_1719];

ALTER TABLE [synergix].[E_YESNO_EXT] WITH CHECK CHECK CONSTRAINT [R_YESNO_EXT_1731];

ALTER TABLE [synergix].[L_ROLE_EXT] WITH CHECK CHECK CONSTRAINT [R_ROLE_EXT_1718];

ALTER TABLE [synergix].[L_ROLE_EXT] WITH CHECK CHECK CONSTRAINT [R_ROLE_EXT_1726];

ALTER TABLE [synergix].[L_YESNO_EXT] WITH CHECK CHECK CONSTRAINT [R_YESNO_EXT_1718];

ALTER TABLE [synergix].[L_YESNO_EXT] WITH CHECK CHECK CONSTRAINT [R_YESNO_EXT_1726];


GO
PRINT N'Update complete.';


GO
