SET XACT_ABORT ON;  -- ★ BEGIN TRY보다 반드시 위에

BEGIN TRY
    BEGIN TRANSACTION;
    SET NOCOUNT ON;
	
	
/*
ALTER TABLE ENERGY.C_REFERENCE NOCHECK  CONSTRAINT [R_SYNERGI_3927];
ALTER TABLE ENERGY.C_REFERENCE NOCHECK CONSTRAINT [R_SYNERGI_3928];
ALTER TABLE ENERGY.X_DOMAIN NOCHECK CONSTRAINT [R_SYNERGI_463];
ALTER TABLE ENERGY.X_DOMAIN NOCHECK CONSTRAINT [R_SYNERGI_763];
ALTER TABLE ENERGY.X_DOMAIN_APPL NOCHECK CONSTRAINT [R_SYNERGI_464];
ALTER TABLE ENERGY.C_CHECK_LIST_CATEGORY NOCHECK CONSTRAINT [R_SYNERGI_3909];
ALTER TABLE ENERGY.X_APPLICATION NOCHECK CONSTRAINT [R_SYNERGI_433];
ALTER TABLE ENERGY.C_CHECK_LIST NOCHECK CONSTRAINT [R_SYNERGI_1279];
ALTER TABLE ENERGY.X_CONNECTION_TYPE NOCHECK CONSTRAINT [R_SYNERGI_3844];
*/	
	


/* (필요시 FK NOCHECK 블록) */

---- 1) DEFINED INSERT ----------------------------------------------------------

INSERT INTO [synergix].[X_CRITERIA] ([CRITERIA], [CRITERIA_SQL], [CRITERIA_TYPE], [SQL_BUILD]) VALUES (50137, N'D_TRANS.STATUS =7', 2, 0)
INSERT INTO [synergix].[X_CRITERIA] ([CRITERIA], [CRITERIA_SQL], [CRITERIA_TYPE], [SQL_BUILD]) VALUES (50138, N'D_TRANS.STATUS =7 
AND D_TRANS.UNIT_RESPONSIBLE  IN (SELECT UNIT FROM <DBO>.A_UNIT WHERE DESCEND_UNIT=326)

', 2, 0)
INSERT INTO [synergix].[X_CRITERIA] ([CRITERIA], [CRITERIA_SQL], [CRITERIA_TYPE], [SQL_BUILD]) VALUES (50139, N'D_TRANS.STATUS =7 
AND D_TRANS.UNIT_RESPONSIBLE  IN (SELECT UNIT FROM <DBO>.A_UNIT WHERE DESCEND_UNIT=3268)

', 2, 0)
INSERT INTO [synergix].[X_CRITERIA] ([CRITERIA], [CRITERIA_SQL], [CRITERIA_TYPE], [SQL_BUILD]) VALUES (50140, N'D_TRANS.STATUS =7 
AND D_TRANS.UNIT_RESPONSIBLE  IN (SELECT UNIT FROM <DBO>.A_UNIT WHERE DESCEND_UNIT=3270)

', 2, 0)
INSERT INTO [synergix].[X_CRITERIA] ([CRITERIA], [CRITERIA_SQL], [CRITERIA_TYPE], [SQL_BUILD]) VALUES (50141, N'D_TRANS.STATUS =7 
AND D_TRANS.UNIT_RESPONSIBLE  IN (SELECT UNIT FROM <DBO>.A_UNIT WHERE DESCEND_UNIT=3261)

', 2, 0)
INSERT INTO [synergix].[X_CRITERIA] ([CRITERIA], [CRITERIA_SQL], [CRITERIA_TYPE], [SQL_BUILD]) VALUES (50142, N'D_TRANS.STATUS =7 
AND D_TRANS.UNIT_RESPONSIBLE  IN (SELECT UNIT FROM <DBO>.A_UNIT WHERE DESCEND_UNIT=3259)

', 2, 0)
INSERT INTO [synergix].[X_CRITERIA] ([CRITERIA], [CRITERIA_SQL], [CRITERIA_TYPE], [SQL_BUILD]) VALUES (50143, N'D_TRANS.STATUS =7 
AND D_TRANS.UNIT_RESPONSIBLE  IN (SELECT UNIT FROM <DBO>.A_UNIT WHERE DESCEND_UNIT=3260)

', 2, 0)
INSERT INTO [synergix].[X_CRITERIA] ([CRITERIA], [CRITERIA_SQL], [CRITERIA_TYPE], [SQL_BUILD]) VALUES (50144, N'D_TRANS.STATUS =7 
AND D_TRANS.UNIT_RESPONSIBLE  IN (SELECT UNIT FROM <DBO>.A_UNIT WHERE DESCEND_UNIT=3257)

', 2, 0)
INSERT INTO [synergix].[X_CRITERIA] ([CRITERIA], [CRITERIA_SQL], [CRITERIA_TYPE], [SQL_BUILD]) VALUES (50145, N'D_TRANS.STATUS =7 
AND D_TRANS.UNIT_RESPONSIBLE  IN (SELECT UNIT FROM <DBO>.A_UNIT WHERE DESCEND_UNIT=3262)

', 2, 0)
INSERT INTO [synergix].[X_CRITERIA] ([CRITERIA], [CRITERIA_SQL], [CRITERIA_TYPE], [SQL_BUILD]) VALUES (50146, N'D_TRANS.STATUS =7 
AND D_TRANS.UNIT_RESPONSIBLE  IN (SELECT UNIT FROM <DBO>.A_UNIT WHERE DESCEND_UNIT=3326)

', 2, 0)
INSERT INTO [synergix].[X_CRITERIA] ([CRITERIA], [CRITERIA_SQL], [CRITERIA_TYPE], [SQL_BUILD]) VALUES (50147, N'D_TRANS.STATUS =7 
AND D_TRANS.UNIT_RESPONSIBLE  IN (SELECT UNIT FROM <DBO>.A_UNIT WHERE DESCEND_UNIT=3332)

', 2, 0)



---- 2) UNDEFINED INSERT --------------------------------------------------------
INSERT INTO [synergix].[X_CRITERIA_OPER] ([CRITERIA], [OPERATION], [APPLICATION], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE]) VALUES (50137, 11, 4, 1, 0)
INSERT INTO [synergix].[X_CRITERIA_OPER] ([CRITERIA], [OPERATION], [APPLICATION], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE]) VALUES (50137, 11, 179, 1, 0)
INSERT INTO [synergix].[X_CRITERIA_OPER] ([CRITERIA], [OPERATION], [APPLICATION], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE]) VALUES (50137, 11, 541, 1, 0)
INSERT INTO [synergix].[X_CRITERIA_OPER] ([CRITERIA], [OPERATION], [APPLICATION], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE]) VALUES (50138, 11, 4, 1, 0)
INSERT INTO [synergix].[X_CRITERIA_OPER] ([CRITERIA], [OPERATION], [APPLICATION], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE]) VALUES (50138, 11, 179, 1, 0)
INSERT INTO [synergix].[X_CRITERIA_OPER] ([CRITERIA], [OPERATION], [APPLICATION], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE]) VALUES (50138, 11, 541, 1, 0)
INSERT INTO [synergix].[X_CRITERIA_OPER] ([CRITERIA], [OPERATION], [APPLICATION], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE]) VALUES (50139, 11, 4, 1, 0)
INSERT INTO [synergix].[X_CRITERIA_OPER] ([CRITERIA], [OPERATION], [APPLICATION], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE]) VALUES (50139, 11, 179, 1, 0)
INSERT INTO [synergix].[X_CRITERIA_OPER] ([CRITERIA], [OPERATION], [APPLICATION], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE]) VALUES (50139, 11, 541, 1, 0)
INSERT INTO [synergix].[X_CRITERIA_OPER] ([CRITERIA], [OPERATION], [APPLICATION], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE]) VALUES (50140, 11, 4, 1, 0)
INSERT INTO [synergix].[X_CRITERIA_OPER] ([CRITERIA], [OPERATION], [APPLICATION], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE]) VALUES (50140, 11, 179, 1, 0)
INSERT INTO [synergix].[X_CRITERIA_OPER] ([CRITERIA], [OPERATION], [APPLICATION], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE]) VALUES (50140, 11, 541, 1, 0)
INSERT INTO [synergix].[X_CRITERIA_OPER] ([CRITERIA], [OPERATION], [APPLICATION], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE]) VALUES (50141, 11, 4, 1, 0)
INSERT INTO [synergix].[X_CRITERIA_OPER] ([CRITERIA], [OPERATION], [APPLICATION], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE]) VALUES (50141, 11, 179, 1, 0)
INSERT INTO [synergix].[X_CRITERIA_OPER] ([CRITERIA], [OPERATION], [APPLICATION], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE]) VALUES (50141, 11, 541, 1, 0)
INSERT INTO [synergix].[X_CRITERIA_OPER] ([CRITERIA], [OPERATION], [APPLICATION], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE]) VALUES (50142, 11, 4, 1, 0)
INSERT INTO [synergix].[X_CRITERIA_OPER] ([CRITERIA], [OPERATION], [APPLICATION], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE]) VALUES (50142, 11, 179, 1, 0)
INSERT INTO [synergix].[X_CRITERIA_OPER] ([CRITERIA], [OPERATION], [APPLICATION], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE]) VALUES (50142, 11, 541, 1, 0)
INSERT INTO [synergix].[X_CRITERIA_OPER] ([CRITERIA], [OPERATION], [APPLICATION], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE]) VALUES (50143, 11, 4, 1, 0)
INSERT INTO [synergix].[X_CRITERIA_OPER] ([CRITERIA], [OPERATION], [APPLICATION], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE]) VALUES (50143, 11, 179, 1, 0)
INSERT INTO [synergix].[X_CRITERIA_OPER] ([CRITERIA], [OPERATION], [APPLICATION], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE]) VALUES (50143, 11, 541, 1, 0)
INSERT INTO [synergix].[X_CRITERIA_OPER] ([CRITERIA], [OPERATION], [APPLICATION], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE]) VALUES (50144, 11, 4, 1, 0)
INSERT INTO [synergix].[X_CRITERIA_OPER] ([CRITERIA], [OPERATION], [APPLICATION], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE]) VALUES (50144, 11, 179, 1, 0)
INSERT INTO [synergix].[X_CRITERIA_OPER] ([CRITERIA], [OPERATION], [APPLICATION], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE]) VALUES (50144, 11, 541, 1, 0)
INSERT INTO [synergix].[X_CRITERIA_OPER] ([CRITERIA], [OPERATION], [APPLICATION], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE]) VALUES (50145, 11, 4, 1, 0)
INSERT INTO [synergix].[X_CRITERIA_OPER] ([CRITERIA], [OPERATION], [APPLICATION], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE]) VALUES (50145, 11, 179, 1, 0)
INSERT INTO [synergix].[X_CRITERIA_OPER] ([CRITERIA], [OPERATION], [APPLICATION], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE]) VALUES (50145, 11, 541, 1, 0)
INSERT INTO [synergix].[X_CRITERIA_OPER] ([CRITERIA], [OPERATION], [APPLICATION], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE]) VALUES (50146, 11, 4, 1, 0)
INSERT INTO [synergix].[X_CRITERIA_OPER] ([CRITERIA], [OPERATION], [APPLICATION], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE]) VALUES (50146, 11, 179, 1, 0)
INSERT INTO [synergix].[X_CRITERIA_OPER] ([CRITERIA], [OPERATION], [APPLICATION], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE]) VALUES (50146, 11, 541, 1, 0)
INSERT INTO [synergix].[X_CRITERIA_OPER] ([CRITERIA], [OPERATION], [APPLICATION], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE]) VALUES (50147, 11, 4, 1, 0)
INSERT INTO [synergix].[X_CRITERIA_OPER] ([CRITERIA], [OPERATION], [APPLICATION], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE]) VALUES (50147, 11, 179, 1, 0)
INSERT INTO [synergix].[X_CRITERIA_OPER] ([CRITERIA], [OPERATION], [APPLICATION], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE]) VALUES (50147, 11, 541, 1, 0)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50136, 11, 4, 2110, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50137, 11, 4, 2109, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50137, 11, 4, 2110, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50137, 11, 179, 2109, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50137, 11, 179, 2110, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50137, 11, 541, 2109, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50137, 11, 541, 2110, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50138, 11, 4, 2109, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50138, 11, 4, 2110, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50138, 11, 179, 2109, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50138, 11, 179, 2110, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50138, 11, 541, 2109, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50138, 11, 541, 2110, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50139, 11, 4, 2109, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50139, 11, 4, 2110, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50139, 11, 179, 2109, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50139, 11, 179, 2110, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50139, 11, 541, 2109, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50139, 11, 541, 2110, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50140, 11, 4, 2109, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50140, 11, 4, 2110, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50140, 11, 179, 2109, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50140, 11, 179, 2110, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50140, 11, 541, 2109, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50140, 11, 541, 2110, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50141, 11, 4, 2109, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50141, 11, 4, 2110, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50141, 11, 179, 2109, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50141, 11, 179, 2110, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50141, 11, 541, 2109, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50141, 11, 541, 2110, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50142, 11, 4, 2109, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50142, 11, 4, 2110, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50142, 11, 179, 2109, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50142, 11, 179, 2110, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50142, 11, 541, 2109, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50142, 11, 541, 2110, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50143, 11, 4, 2109, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50143, 11, 4, 2110, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50143, 11, 179, 2109, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50143, 11, 179, 2110, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50143, 11, 541, 2109, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50143, 11, 541, 2110, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50144, 11, 4, 2109, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50144, 11, 4, 2110, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50144, 11, 179, 2109, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50144, 11, 179, 2110, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50144, 11, 541, 2109, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50144, 11, 541, 2110, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50145, 11, 4, 2109, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50145, 11, 4, 2110, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50145, 11, 179, 2109, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50145, 11, 179, 2110, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50145, 11, 541, 2109, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50145, 11, 541, 2110, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50146, 11, 4, 2109, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50146, 11, 4, 2110, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50146, 11, 179, 2109, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50146, 11, 179, 2110, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50146, 11, 541, 2109, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50146, 11, 541, 2110, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50147, 11, 4, 2109, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50147, 11, 4, 2110, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50147, 11, 179, 2109, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50147, 11, 179, 2110, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50147, 11, 541, 2109, 1, 0, 1, NULL, NULL)
INSERT INTO [synergix].[X_CRITERIA_OPER_DOMAIN] ([CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN], [FLG_ACTIVE], [FLG_DEFAULT_ACTIVE], [SEQUENCE], [DOMAIN_BLOB], [TEXT]) VALUES (50147, 11, 541, 2110, 1, 0, 1, NULL, NULL)




INSERT INTO [synergix].[C_SUBSCRIBER_ALERT] ([SUBSCRIBER_GROUP], [CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN]) VALUES (34, 50138, 11, 179, 2109)
INSERT INTO [synergix].[C_SUBSCRIBER_ALERT] ([SUBSCRIBER_GROUP], [CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN]) VALUES (34, 50138, 11, 541, 2109)
INSERT INTO [synergix].[C_SUBSCRIBER_ALERT] ([SUBSCRIBER_GROUP], [CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN]) VALUES (35, 50139, 11, 179, 2109)
INSERT INTO [synergix].[C_SUBSCRIBER_ALERT] ([SUBSCRIBER_GROUP], [CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN]) VALUES (35, 50139, 11, 541, 2109)
INSERT INTO [synergix].[C_SUBSCRIBER_ALERT] ([SUBSCRIBER_GROUP], [CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN]) VALUES (36, 50140, 11, 179, 2109)
INSERT INTO [synergix].[C_SUBSCRIBER_ALERT] ([SUBSCRIBER_GROUP], [CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN]) VALUES (36, 50140, 11, 541, 2109)
INSERT INTO [synergix].[C_SUBSCRIBER_ALERT] ([SUBSCRIBER_GROUP], [CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN]) VALUES (37, 50141, 11, 179, 2109)
INSERT INTO [synergix].[C_SUBSCRIBER_ALERT] ([SUBSCRIBER_GROUP], [CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN]) VALUES (37, 50141, 11, 541, 2109)
INSERT INTO [synergix].[C_SUBSCRIBER_ALERT] ([SUBSCRIBER_GROUP], [CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN]) VALUES (38, 50142, 11, 179, 2109)
INSERT INTO [synergix].[C_SUBSCRIBER_ALERT] ([SUBSCRIBER_GROUP], [CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN]) VALUES (38, 50142, 11, 541, 2109)
INSERT INTO [synergix].[C_SUBSCRIBER_ALERT] ([SUBSCRIBER_GROUP], [CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN]) VALUES (39, 50143, 11, 179, 2109)
INSERT INTO [synergix].[C_SUBSCRIBER_ALERT] ([SUBSCRIBER_GROUP], [CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN]) VALUES (39, 50143, 11, 541, 2109)
INSERT INTO [synergix].[C_SUBSCRIBER_ALERT] ([SUBSCRIBER_GROUP], [CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN]) VALUES (40, 50144, 11, 179, 2109)
INSERT INTO [synergix].[C_SUBSCRIBER_ALERT] ([SUBSCRIBER_GROUP], [CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN]) VALUES (40, 50144, 11, 541, 2109)
INSERT INTO [synergix].[C_SUBSCRIBER_ALERT] ([SUBSCRIBER_GROUP], [CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN]) VALUES (41, 50145, 11, 179, 2109)
INSERT INTO [synergix].[C_SUBSCRIBER_ALERT] ([SUBSCRIBER_GROUP], [CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN]) VALUES (41, 50145, 11, 541, 2109)
INSERT INTO [synergix].[C_SUBSCRIBER_ALERT] ([SUBSCRIBER_GROUP], [CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN]) VALUES (42, 50146, 11, 179, 2109)
INSERT INTO [synergix].[C_SUBSCRIBER_ALERT] ([SUBSCRIBER_GROUP], [CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN]) VALUES (42, 50146, 11, 541, 2109)
INSERT INTO [synergix].[C_SUBSCRIBER_ALERT] ([SUBSCRIBER_GROUP], [CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN]) VALUES (43, 50147, 11, 179, 2109)
INSERT INTO [synergix].[C_SUBSCRIBER_ALERT] ([SUBSCRIBER_GROUP], [CRITERIA], [OPERATION], [APPLICATION], [ROOT_DOMAIN]) VALUES (43, 50147, 11, 541, 2109)



---- 3) UNDEFINED UPDATE --------------------------------------------------------

---- 4) DEFINED UPDATE (REVERSE) ------------------------------------------------
UPDATE [synergix].[X_CRITERIA] SET [CRITERIA_SQL]=N'NOT ((D_TRANS.APPLICATION = 541 
AND  EXISTS(SELECT 1 FROM SYNERGIX.P_EXTRA_INFO WHERE PERSON  =<LOGGED_ON_PERSON> AND EXTRA_INFO =1 AND VALUE_CODE =1) ) 
OR 
(EXISTS(select 1 from synergix.A_APPLICATION where descend_APPLICATION = 179 AND APPLICATION = D_TRANS.APPLICATION)
AND  EXISTS(SELECT 1 FROM SYNERGIX.P_EXTRA_INFO WHERE PERSON  =<LOGGED_ON_PERSON> AND EXTRA_INFO =2 AND VALUE_CODE =1) )    )
  ' WHERE [CRITERIA]=50132

---- 5) UNDEFINED DELETE --------------------------------------------------------

---- 6) DEFINED DELETE (REVERSE) ------------------------------------------------

DELETE FROM [synergix].[C_SUBSCRIBER_ALERT] WHERE [SUBSCRIBER_GROUP]=46 AND [CRITERIA]=50130 AND [OPERATION]=11 AND [APPLICATION]=541 AND [ROOT_DOMAIN]=2109
DELETE FROM [synergix].[C_SUBSCRIBER_ALERT] WHERE [SUBSCRIBER_GROUP]=46 AND [CRITERIA]=50130 AND [OPERATION]=11 AND [APPLICATION]=179 AND [ROOT_DOMAIN]=2109
DELETE FROM [synergix].[C_SUBSCRIBER_MEMBERS] WHERE [SUBSCRIBER_GROUP]=46 AND [MEMBER_NO]=1
DELETE FROM [synergix].[Ｌ_SUBSCRIBER_GROUP] WHERE [SUBSCRIBER_GROUP]=46
DELETE FROM [synergix].[C_SUBSCRIBER_GROUP] WHERE [SUBSCRIBER_GROUP]=46


/*
ALTER TABLE ENERGY.C_REFERENCE CHECK  CONSTRAINT [R_SYNERGI_3927];
ALTER TABLE ENERGY.C_REFERENCE CHECK CONSTRAINT [R_SYNERGI_3928];
ALTER TABLE ENERGY.X_DOMAIN_APPL CHECK CONSTRAINT [R_SYNERGI_464];
ALTER TABLE ENERGY.X_DOMAIN CHECK CONSTRAINT [R_SYNERGI_463];
ALTER TABLE ENERGY.X_DOMAIN CHECK CONSTRAINT [R_SYNERGI_763];
ALTER TABLE ENERGY.C_CHECK_LIST_CATEGORY CHECK CONSTRAINT [R_SYNERGI_3909];
ALTER TABLE ENERGY.X_APPLICATION CHECK CONSTRAINT [R_SYNERGI_433];
ALTER TABLE ENERGY.C_CHECK_LIST CHECK CONSTRAINT [R_SYNERGI_1279];
ALTER TABLE ENERGY.X_CONNECTION_TYPE CHECK CONSTRAINT [R_SYNERGI_3844];
*/

    SET NOCOUNT OFF;
    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0
        ROLLBACK TRANSACTION;

    THROW; -- 오류 재전파
END CATCH

