SET XACT_ABORT ON;  -- ★ BEGIN TRY보다 반드시 위에

BEGIN TRY
    BEGIN TRANSACTION;
    SET NOCOUNT ON;
	
	
/*
ALTER TABLE ENERGY.C_REFERENCE NOCHECK  CONSTRAINT [R_SYNERGI_3927];
ALTER TABLE ENERGY.C_REFERENCE NOCHECK CONSTRAINT [R_SYNERGI_3928];
ALTER TABLE ENERGY.X_DOMAIN NOCHECK CONSTRAINT [R_SYNERGI_463];
ALTER TABLE ENERGY.X_DOMAIN NOCHECK CONSTRAINT [R_SYNERGI_763];
ALTER TABLE ENERGY.X_DOMAIN_APPL NOCHECK CONSTRAINT [R_SYNERGI_464];
ALTER TABLE ENERGY.C_CHECK_LIST_CATEGORY NOCHECK CONSTRAINT [R_SYNERGI_3909];
ALTER TABLE ENERGY.X_APPLICATION NOCHECK CONSTRAINT [R_SYNERGI_433];
ALTER TABLE ENERGY.C_CHECK_LIST NOCHECK CONSTRAINT [R_SYNERGI_1279];
ALTER TABLE ENERGY.X_CONNECTION_TYPE NOCHECK CONSTRAINT [R_SYNERGI_3844];
*/	
	


/* (필요시 FK NOCHECK 블록) */

---- 1) DEFINED INSERT ----------------------------------------------------------
INSERT INTO [synergix].[C_ROLE_EXT] ([ROLE_EXT], [DISABLED], [SEQUENCE]) VALUES (3254, NULL, NULL)
INSERT INTO [synergix].[C_ROLE_EXT] ([ROLE_EXT], [DISABLED], [SEQUENCE]) VALUES (3257, NULL, NULL)
INSERT INTO [synergix].[C_ROLE_EXT] ([ROLE_EXT], [DISABLED], [SEQUENCE]) VALUES (3260, NULL, NULL)
INSERT INTO [synergix].[C_ROLE_EXT] ([ROLE_EXT], [DISABLED], [SEQUENCE]) VALUES (3261, NULL, NULL)
INSERT INTO [synergix].[C_ROLE_EXT] ([ROLE_EXT], [DISABLED], [SEQUENCE]) VALUES (3262, NULL, NULL)
INSERT INTO [synergix].[C_ROLE_EXT] ([ROLE_EXT], [DISABLED], [SEQUENCE]) VALUES (3268, NULL, NULL)
INSERT INTO [synergix].[C_ROLE_EXT] ([ROLE_EXT], [DISABLED], [SEQUENCE]) VALUES (3270, NULL, NULL)
INSERT INTO [synergix].[C_ROLE_EXT] ([ROLE_EXT], [DISABLED], [SEQUENCE]) VALUES (3271, NULL, NULL)
INSERT INTO [synergix].[C_ROLE_EXT] ([ROLE_EXT], [DISABLED], [SEQUENCE]) VALUES (3313, NULL, NULL)
INSERT INTO [synergix].[C_ROLE_EXT] ([ROLE_EXT], [DISABLED], [SEQUENCE]) VALUES (3332, NULL, NULL)
INSERT INTO [synergix].[C_ROLE_EXT] ([ROLE_EXT], [DISABLED], [SEQUENCE]) VALUES (3434, NULL, NULL)
INSERT INTO [synergix].[C_ROLE_EXT] ([ROLE_EXT], [DISABLED], [SEQUENCE]) VALUES (3447, NULL, NULL)
INSERT INTO [synergix].[C_ROLE_EXT] ([ROLE_EXT], [DISABLED], [SEQUENCE]) VALUES (4160, NULL, NULL)
INSERT INTO [synergix].[C_ROLE_EXT] ([ROLE_EXT], [DISABLED], [SEQUENCE]) VALUES (4182, NULL, NULL)
INSERT INTO [synergix].[C_ROLE_EXT] ([ROLE_EXT], [DISABLED], [SEQUENCE]) VALUES (4183, NULL, NULL)
INSERT INTO [synergix].[C_ROLE_EXT] ([ROLE_EXT], [DISABLED], [SEQUENCE]) VALUES (4188, NULL, NULL)
INSERT INTO [synergix].[C_ROLE_EXT] ([ROLE_EXT], [DISABLED], [SEQUENCE]) VALUES (4200, NULL, NULL)
INSERT INTO [synergix].[C_ROLE_EXT] ([ROLE_EXT], [DISABLED], [SEQUENCE]) VALUES (4205, NULL, NULL)
INSERT INTO [synergix].[C_ROLE_EXT] ([ROLE_EXT], [DISABLED], [SEQUENCE]) VALUES (4268, NULL, NULL)
INSERT INTO [synergix].[C_ROLE_EXT] ([ROLE_EXT], [DISABLED], [SEQUENCE]) VALUES (4269, NULL, NULL)
INSERT INTO [synergix].[C_ROLE_EXT] ([ROLE_EXT], [DISABLED], [SEQUENCE]) VALUES (4396, NULL, NULL)
INSERT INTO [synergix].[C_ROLE_EXT] ([ROLE_EXT], [DISABLED], [SEQUENCE]) VALUES (4397, NULL, NULL)
INSERT INTO [synergix].[C_ROLE_EXT] ([ROLE_EXT], [DISABLED], [SEQUENCE]) VALUES (4402, NULL, NULL)
INSERT INTO [synergix].[C_ROLE_EXT] ([ROLE_EXT], [DISABLED], [SEQUENCE]) VALUES (4403, NULL, NULL)

---- 2) UNDEFINED INSERT --------------------------------------------------------
INSERT INTO [synergix].[L_ROLE_EXT] ([ROLE_EXT], [LANGUAGE], [DESCRIPTION]) VALUES (3254, 1, N'Engineering and Construction')
INSERT INTO [synergix].[L_ROLE_EXT] ([ROLE_EXT], [LANGUAGE], [DESCRIPTION]) VALUES (3254, 2, N'Engineering and Construction')
INSERT INTO [synergix].[L_ROLE_EXT] ([ROLE_EXT], [LANGUAGE], [DESCRIPTION]) VALUES (3257, 1, N'Operations and Maintenance - HUC & Commissioning')
INSERT INTO [synergix].[L_ROLE_EXT] ([ROLE_EXT], [LANGUAGE], [DESCRIPTION]) VALUES (3257, 2, N'Operations and Maintenance - HUC & Commissioning')
INSERT INTO [synergix].[L_ROLE_EXT] ([ROLE_EXT], [LANGUAGE], [DESCRIPTION]) VALUES (3260, 1, N'Engineering and Construction - Total Marine Technology')
INSERT INTO [synergix].[L_ROLE_EXT] ([ROLE_EXT], [LANGUAGE], [DESCRIPTION]) VALUES (3260, 2, N'Engineering and Construction - Total Marine Technology')
INSERT INTO [synergix].[L_ROLE_EXT] ([ROLE_EXT], [LANGUAGE], [DESCRIPTION]) VALUES (3261, 1, N'Operations and Maintenance - Technology Solutions')
INSERT INTO [synergix].[L_ROLE_EXT] ([ROLE_EXT], [LANGUAGE], [DESCRIPTION]) VALUES (3261, 2, N'Operations and Maintenance - Technology Solutions')
INSERT INTO [synergix].[L_ROLE_EXT] ([ROLE_EXT], [LANGUAGE], [DESCRIPTION]) VALUES (3262, 1, N'Operations and Maintenance - Geosciences')
INSERT INTO [synergix].[L_ROLE_EXT] ([ROLE_EXT], [LANGUAGE], [DESCRIPTION]) VALUES (3262, 2, N'Operations and Maintenance - Geosciences')
INSERT INTO [synergix].[L_ROLE_EXT] ([ROLE_EXT], [LANGUAGE], [DESCRIPTION]) VALUES (3268, 1, N'Engineering and Construction - Lumut Fabrication Unit')
INSERT INTO [synergix].[L_ROLE_EXT] ([ROLE_EXT], [LANGUAGE], [DESCRIPTION]) VALUES (3268, 2, N'Engineering and Construction - Lumut Fabrication Unit')
INSERT INTO [synergix].[L_ROLE_EXT] ([ROLE_EXT], [LANGUAGE], [DESCRIPTION]) VALUES (3270, 1, N'Engineering and Construction - Sapura Energy Australia')
INSERT INTO [synergix].[L_ROLE_EXT] ([ROLE_EXT], [LANGUAGE], [DESCRIPTION]) VALUES (3270, 2, N'Engineering and Construction - Sapura Energy Australia')
INSERT INTO [synergix].[L_ROLE_EXT] ([ROLE_EXT], [LANGUAGE], [DESCRIPTION]) VALUES (3271, 1, N'Engineering and Construction - Engineering Solution')
INSERT INTO [synergix].[L_ROLE_EXT] ([ROLE_EXT], [LANGUAGE], [DESCRIPTION]) VALUES (3271, 2, N'Engineering and Construction - Engineering Solution')
INSERT INTO [synergix].[L_ROLE_EXT] ([ROLE_EXT], [LANGUAGE], [DESCRIPTION]) VALUES (3313, 1, N'Drilling')
INSERT INTO [synergix].[L_ROLE_EXT] ([ROLE_EXT], [LANGUAGE], [DESCRIPTION]) VALUES (3313, 2, N'Drilling')
INSERT INTO [synergix].[L_ROLE_EXT] ([ROLE_EXT], [LANGUAGE], [DESCRIPTION]) VALUES (3332, 1, N'Engineering and Construction - Assets Management')
INSERT INTO [synergix].[L_ROLE_EXT] ([ROLE_EXT], [LANGUAGE], [DESCRIPTION]) VALUES (3332, 2, N'Engineering and Construction - Assets Management')
INSERT INTO [synergix].[L_ROLE_EXT] ([ROLE_EXT], [LANGUAGE], [DESCRIPTION]) VALUES (3434, 1, N'Shared Services')
INSERT INTO [synergix].[L_ROLE_EXT] ([ROLE_EXT], [LANGUAGE], [DESCRIPTION]) VALUES (3434, 2, N'Shared Services')
INSERT INTO [synergix].[L_ROLE_EXT] ([ROLE_EXT], [LANGUAGE], [DESCRIPTION]) VALUES (3447, 1, N'Engineering and Construction - Assets Management - Asset ')
INSERT INTO [synergix].[L_ROLE_EXT] ([ROLE_EXT], [LANGUAGE], [DESCRIPTION]) VALUES (3447, 2, N'Engineering and Construction - Assets Management - Asset ')
INSERT INTO [synergix].[L_ROLE_EXT] ([ROLE_EXT], [LANGUAGE], [DESCRIPTION]) VALUES (4160, 1, N'Operations and Maintenance - Sapura Baker Hughes')
INSERT INTO [synergix].[L_ROLE_EXT] ([ROLE_EXT], [LANGUAGE], [DESCRIPTION]) VALUES (4160, 2, N'Operations and Maintenance - Sapura Baker Hughes')
INSERT INTO [synergix].[L_ROLE_EXT] ([ROLE_EXT], [LANGUAGE], [DESCRIPTION]) VALUES (4182, 1, N'Operations and Maintenance')
INSERT INTO [synergix].[L_ROLE_EXT] ([ROLE_EXT], [LANGUAGE], [DESCRIPTION]) VALUES (4182, 2, N'Operations and Maintenance')
INSERT INTO [synergix].[L_ROLE_EXT] ([ROLE_EXT], [LANGUAGE], [DESCRIPTION]) VALUES (4183, 1, N'Engineering and Construction - E&C Malaysia')
INSERT INTO [synergix].[L_ROLE_EXT] ([ROLE_EXT], [LANGUAGE], [DESCRIPTION]) VALUES (4183, 2, N'Engineering and Construction - E&C Malaysia')
INSERT INTO [synergix].[L_ROLE_EXT] ([ROLE_EXT], [LANGUAGE], [DESCRIPTION]) VALUES (4188, 1, N'Sapura JV')
INSERT INTO [synergix].[L_ROLE_EXT] ([ROLE_EXT], [LANGUAGE], [DESCRIPTION]) VALUES (4188, 2, N'Sapura JV')
INSERT INTO [synergix].[L_ROLE_EXT] ([ROLE_EXT], [LANGUAGE], [DESCRIPTION]) VALUES (4200, 1, N'Operations and Maintenance - OSV')
INSERT INTO [synergix].[L_ROLE_EXT] ([ROLE_EXT], [LANGUAGE], [DESCRIPTION]) VALUES (4200, 2, N'Operations and Maintenance - OSV')
INSERT INTO [synergix].[L_ROLE_EXT] ([ROLE_EXT], [LANGUAGE], [DESCRIPTION]) VALUES (4205, 1, N'Operations and Maintenance - Sapura Subsea Services')
INSERT INTO [synergix].[L_ROLE_EXT] ([ROLE_EXT], [LANGUAGE], [DESCRIPTION]) VALUES (4205, 2, N'Operations and Maintenance - Sapura Subsea Services')
INSERT INTO [synergix].[L_ROLE_EXT] ([ROLE_EXT], [LANGUAGE], [DESCRIPTION]) VALUES (4268, 1, N'Engineering and Construction - Sapura Energy Thailand')
INSERT INTO [synergix].[L_ROLE_EXT] ([ROLE_EXT], [LANGUAGE], [DESCRIPTION]) VALUES (4268, 2, N'Engineering and Construction - Sapura Energy Thailand')
INSERT INTO [synergix].[L_ROLE_EXT] ([ROLE_EXT], [LANGUAGE], [DESCRIPTION]) VALUES (4269, 1, N'Engineering and Construction - AFMED')
INSERT INTO [synergix].[L_ROLE_EXT] ([ROLE_EXT], [LANGUAGE], [DESCRIPTION]) VALUES (4269, 2, N'Engineering and Construction - AFMED')
INSERT INTO [synergix].[L_ROLE_EXT] ([ROLE_EXT], [LANGUAGE], [DESCRIPTION]) VALUES (4396, 1, N'Engineering and Construction - Global Project Centre')
INSERT INTO [synergix].[L_ROLE_EXT] ([ROLE_EXT], [LANGUAGE], [DESCRIPTION]) VALUES (4396, 2, N'Engineering and Construction - Global Project Centre')
INSERT INTO [synergix].[L_ROLE_EXT] ([ROLE_EXT], [LANGUAGE], [DESCRIPTION]) VALUES (4397, 1, N'Engineering and Construction - LATAM')
INSERT INTO [synergix].[L_ROLE_EXT] ([ROLE_EXT], [LANGUAGE], [DESCRIPTION]) VALUES (4397, 2, N'Engineering and Construction - LATAM')
INSERT INTO [synergix].[L_ROLE_EXT] ([ROLE_EXT], [LANGUAGE], [DESCRIPTION]) VALUES (4402, 1, N'Engineering and Construction - Commercial & Contracts')
INSERT INTO [synergix].[L_ROLE_EXT] ([ROLE_EXT], [LANGUAGE], [DESCRIPTION]) VALUES (4402, 2, N'Engineering and Construction - Commercial & Contracts')
INSERT INTO [synergix].[L_ROLE_EXT] ([ROLE_EXT], [LANGUAGE], [DESCRIPTION]) VALUES (4403, 1, N'Engineering and Construction - BD & Strategic Planning')
INSERT INTO [synergix].[L_ROLE_EXT] ([ROLE_EXT], [LANGUAGE], [DESCRIPTION]) VALUES (4403, 2, N'Engineering and Construction - BD & Strategic Planning')
INSERT INTO [synergix].[X_DOMAIN_READ_ONLY] ([DOMAIN], [APPLICATION], [STATUS], [CRITERIA], [FLG_ACTIVE]) VALUES (50202, 4, 0, 50135, 1)
INSERT INTO [synergix].[L_CRITERIA] ([CRITERIA], [LANGUAGE], [DESCRIPTION], [LONG_DESCRIPTION]) VALUES (50137, 2, N'TOE - All Verified notification', NULL)
INSERT INTO [synergix].[L_CRITERIA] ([CRITERIA], [LANGUAGE], [DESCRIPTION], [LONG_DESCRIPTION]) VALUES (50137, 22, N'TOE - All Verified notification', NULL)
INSERT INTO [synergix].[L_CRITERIA] ([CRITERIA], [LANGUAGE], [DESCRIPTION], [LONG_DESCRIPTION]) VALUES (50138, 2, N'TOE - SOSB Verified notification', NULL)
INSERT INTO [synergix].[L_CRITERIA] ([CRITERIA], [LANGUAGE], [DESCRIPTION], [LONG_DESCRIPTION]) VALUES (50138, 22, N'TOE - SOSB Verified notification', NULL)
INSERT INTO [synergix].[L_CRITERIA] ([CRITERIA], [LANGUAGE], [DESCRIPTION], [LONG_DESCRIPTION]) VALUES (50139, 2, N'TOE - SFSB Verified notification', NULL)
INSERT INTO [synergix].[L_CRITERIA] ([CRITERIA], [LANGUAGE], [DESCRIPTION], [LONG_DESCRIPTION]) VALUES (50139, 22, N'TOE - SFSB Verified notification', NULL)
INSERT INTO [synergix].[L_CRITERIA] ([CRITERIA], [LANGUAGE], [DESCRIPTION], [LONG_DESCRIPTION]) VALUES (50140, 2, N'TOE - SEA Verified notification', NULL)
INSERT INTO [synergix].[L_CRITERIA] ([CRITERIA], [LANGUAGE], [DESCRIPTION], [LONG_DESCRIPTION]) VALUES (50140, 22, N'TOE - SEA Verified notification', NULL)
INSERT INTO [synergix].[L_CRITERIA] ([CRITERIA], [LANGUAGE], [DESCRIPTION], [LONG_DESCRIPTION]) VALUES (50141, 2, N'TOE - STS Verified notification', NULL)
INSERT INTO [synergix].[L_CRITERIA] ([CRITERIA], [LANGUAGE], [DESCRIPTION], [LONG_DESCRIPTION]) VALUES (50141, 22, N'TOE - STS Verified notification', NULL)
INSERT INTO [synergix].[L_CRITERIA] ([CRITERIA], [LANGUAGE], [DESCRIPTION], [LONG_DESCRIPTION]) VALUES (50142, 2, N'TOE - SSS Verified notification', NULL)
INSERT INTO [synergix].[L_CRITERIA] ([CRITERIA], [LANGUAGE], [DESCRIPTION], [LONG_DESCRIPTION]) VALUES (50142, 22, N'TOE - SSS Verified notification', NULL)
INSERT INTO [synergix].[L_CRITERIA] ([CRITERIA], [LANGUAGE], [DESCRIPTION], [LONG_DESCRIPTION]) VALUES (50143, 2, N'TOE - TMT Verified notification', NULL)
INSERT INTO [synergix].[L_CRITERIA] ([CRITERIA], [LANGUAGE], [DESCRIPTION], [LONG_DESCRIPTION]) VALUES (50143, 22, N'TOE - TMT Verified notification', NULL)
INSERT INTO [synergix].[L_CRITERIA] ([CRITERIA], [LANGUAGE], [DESCRIPTION], [LONG_DESCRIPTION]) VALUES (50144, 2, N'TOE - SPSB Verified notification', NULL)
INSERT INTO [synergix].[L_CRITERIA] ([CRITERIA], [LANGUAGE], [DESCRIPTION], [LONG_DESCRIPTION]) VALUES (50144, 22, N'TOE - SPSB Verified notification', NULL)
INSERT INTO [synergix].[L_CRITERIA] ([CRITERIA], [LANGUAGE], [DESCRIPTION], [LONG_DESCRIPTION]) VALUES (50145, 2, N'TOE - SGSB Verified notification', NULL)
INSERT INTO [synergix].[L_CRITERIA] ([CRITERIA], [LANGUAGE], [DESCRIPTION], [LONG_DESCRIPTION]) VALUES (50145, 22, N'TOE - SGSB Verified notification', NULL)
INSERT INTO [synergix].[L_CRITERIA] ([CRITERIA], [LANGUAGE], [DESCRIPTION], [LONG_DESCRIPTION]) VALUES (50146, 2, N'TOE - SD Verified notification', NULL)
INSERT INTO [synergix].[L_CRITERIA] ([CRITERIA], [LANGUAGE], [DESCRIPTION], [LONG_DESCRIPTION]) VALUES (50146, 22, N'TOE - SD Verified notification', NULL)
INSERT INTO [synergix].[L_CRITERIA] ([CRITERIA], [LANGUAGE], [DESCRIPTION], [LONG_DESCRIPTION]) VALUES (50147, 2, N'TOE - SAM Verified notification', NULL)
INSERT INTO [synergix].[L_CRITERIA] ([CRITERIA], [LANGUAGE], [DESCRIPTION], [LONG_DESCRIPTION]) VALUES (50147, 22, N'TOE - SAM Verified notification', NULL)

---- 3) UNDEFINED UPDATE --------------------------------------------------------
UPDATE [synergix].[X_EXTRA_INFO] SET [CODETABLE_EXTRA_INFO]=50001 WHERE [EXTRA_INFO]=1
UPDATE [synergix].[X_EXTRA_INFO] SET [CODETABLE_EXTRA_INFO]=50001 WHERE [EXTRA_INFO]=2

---- 4) DEFINED UPDATE (REVERSE) ------------------------------------------------
UPDATE [synergix].[X_CRITERIA] SET [CRITERIA_SQL]=N'D_TRANS.STATUS =7 
AND D_TRANS.UNIT_RESPONSIBLE  IN (SELECT UNIT FROM <DBO>.A_UNIT WHERE DESCEND_UNIT=3332)

' WHERE [CRITERIA]=50147
UPDATE [synergix].[X_CRITERIA] SET [CRITERIA_SQL]=N'D_TRANS.STATUS =7 
AND D_TRANS.UNIT_RESPONSIBLE  IN (SELECT UNIT FROM <DBO>.A_UNIT WHERE DESCEND_UNIT=3326)

' WHERE [CRITERIA]=50146
UPDATE [synergix].[X_CRITERIA] SET [CRITERIA_SQL]=N'D_TRANS.STATUS =7 
AND D_TRANS.UNIT_RESPONSIBLE  IN (SELECT UNIT FROM <DBO>.A_UNIT WHERE DESCEND_UNIT=3262)

' WHERE [CRITERIA]=50145
UPDATE [synergix].[X_CRITERIA] SET [CRITERIA_SQL]=N'D_TRANS.STATUS =7 
AND D_TRANS.UNIT_RESPONSIBLE  IN (SELECT UNIT FROM <DBO>.A_UNIT WHERE DESCEND_UNIT=3257)

' WHERE [CRITERIA]=50144
UPDATE [synergix].[X_CRITERIA] SET [CRITERIA_SQL]=N'D_TRANS.STATUS =7 
AND D_TRANS.UNIT_RESPONSIBLE  IN (SELECT UNIT FROM <DBO>.A_UNIT WHERE DESCEND_UNIT=3260)

' WHERE [CRITERIA]=50143
UPDATE [synergix].[X_CRITERIA] SET [CRITERIA_SQL]=N'D_TRANS.STATUS =7 
AND D_TRANS.UNIT_RESPONSIBLE  IN (SELECT UNIT FROM <DBO>.A_UNIT WHERE DESCEND_UNIT=3259)

' WHERE [CRITERIA]=50142
UPDATE [synergix].[X_CRITERIA] SET [CRITERIA_SQL]=N'D_TRANS.STATUS =7 
AND D_TRANS.UNIT_RESPONSIBLE  IN (SELECT UNIT FROM <DBO>.A_UNIT WHERE DESCEND_UNIT=3261)

' WHERE [CRITERIA]=50141
UPDATE [synergix].[X_CRITERIA] SET [CRITERIA_SQL]=N'D_TRANS.STATUS =7 
AND D_TRANS.UNIT_RESPONSIBLE  IN (SELECT UNIT FROM <DBO>.A_UNIT WHERE DESCEND_UNIT=3270)

' WHERE [CRITERIA]=50140
UPDATE [synergix].[X_CRITERIA] SET [CRITERIA_SQL]=N'D_TRANS.STATUS =7 
AND D_TRANS.UNIT_RESPONSIBLE  IN (SELECT UNIT FROM <DBO>.A_UNIT WHERE DESCEND_UNIT=3268)

' WHERE [CRITERIA]=50139
UPDATE [synergix].[X_CRITERIA] SET [CRITERIA_SQL]=N'D_TRANS.STATUS =7 
AND D_TRANS.UNIT_RESPONSIBLE  IN (SELECT UNIT FROM <DBO>.A_UNIT WHERE DESCEND_UNIT=3267)

' WHERE [CRITERIA]=50138
UPDATE [synergix].[X_CRITERIA] SET [CRITERIA_SQL]=N'NOT ((D_TRANS.APPLICATION = 541 
AND  EXISTS(SELECT 1 FROM SYNERGIX.P_EXTRA_INFO WHERE PERSON  =<LOGGED_ON_PERSON> AND EXTRA_INFO =1 
          AND VALUE_CODE IN   (SELECT DESCEND_UNIT FROM  <DBO>.A_UNIT WHERE UNIT  = D_TRANS.UNIT_RESPONSIBLE)   ) ) 
OR 
(EXISTS(select 1 from synergix.A_APPLICATION where descend_APPLICATION = 179 AND APPLICATION = D_TRANS.APPLICATION)
AND  EXISTS(SELECT 1 FROM SYNERGIX.P_EXTRA_INFO WHERE PERSON  =<LOGGED_ON_PERSON> AND EXTRA_INFO =2 
       AND VALUE_CODE IN   (SELECT DESCEND_UNIT FROM  <DBO>.A_UNIT WHERE UNIT  = D_TRANS.UNIT_RESPONSIBLE)   ) )   
 )

  ' WHERE [CRITERIA]=50132
UPDATE [synergix].[X_CRITERIA] SET [CRITERIA_SQL]=N'(SYNERGIX.EXIST_SYNERGI_REFERENCE_OPTION(<TRANS>,210,1) = 0 OR D_TRANS.STATUS =0 )' WHERE [CRITERIA]=50131
UPDATE [synergix].[X_CRITERIA] SET [CRITERIA_SQL]=N'EXISTS (SELECT * FROM <DBO>.D_SYNERGI D_SYNERGI     WHERE D_SYNERGI.TRANS = D_TRANS.TRANS)   AND D_TRANS.STATUS =7 ' WHERE [CRITERIA]=50103

---- 5) UNDEFINED DELETE --------------------------------------------------------
DELETE FROM [synergix].[L_ROLE_EXT] WHERE [ROLE_EXT]=1 AND [LANGUAGE]=1
DELETE FROM [synergix].[L_ROLE_EXT] WHERE [ROLE_EXT]=1 AND [LANGUAGE]=2
DELETE FROM [synergix].[L_ROLE_EXT] WHERE [ROLE_EXT]=2 AND [LANGUAGE]=1
DELETE FROM [synergix].[L_ROLE_EXT] WHERE [ROLE_EXT]=2 AND [LANGUAGE]=2

---- 6) DEFINED DELETE (REVERSE) ------------------------------------------------
DELETE FROM [synergix].[C_SUBSCRIBER_ALERT] WHERE [SUBSCRIBER_GROUP]=43 AND [CRITERIA]=50114 AND [OPERATION]=11 AND [APPLICATION]=541 AND [ROOT_DOMAIN]=2109
DELETE FROM [synergix].[C_SUBSCRIBER_ALERT] WHERE [SUBSCRIBER_GROUP]=42 AND [CRITERIA]=50113 AND [OPERATION]=11 AND [APPLICATION]=541 AND [ROOT_DOMAIN]=2109
DELETE FROM [synergix].[C_SUBSCRIBER_ALERT] WHERE [SUBSCRIBER_GROUP]=41 AND [CRITERIA]=50112 AND [OPERATION]=11 AND [APPLICATION]=541 AND [ROOT_DOMAIN]=2109
DELETE FROM [synergix].[C_SUBSCRIBER_ALERT] WHERE [SUBSCRIBER_GROUP]=40 AND [CRITERIA]=50111 AND [OPERATION]=11 AND [APPLICATION]=541 AND [ROOT_DOMAIN]=2109
DELETE FROM [synergix].[C_SUBSCRIBER_ALERT] WHERE [SUBSCRIBER_GROUP]=39 AND [CRITERIA]=50110 AND [OPERATION]=11 AND [APPLICATION]=541 AND [ROOT_DOMAIN]=2109
DELETE FROM [synergix].[C_SUBSCRIBER_ALERT] WHERE [SUBSCRIBER_GROUP]=38 AND [CRITERIA]=50109 AND [OPERATION]=11 AND [APPLICATION]=541 AND [ROOT_DOMAIN]=2109
DELETE FROM [synergix].[C_SUBSCRIBER_ALERT] WHERE [SUBSCRIBER_GROUP]=37 AND [CRITERIA]=50108 AND [OPERATION]=11 AND [APPLICATION]=541 AND [ROOT_DOMAIN]=2109
DELETE FROM [synergix].[C_SUBSCRIBER_ALERT] WHERE [SUBSCRIBER_GROUP]=36 AND [CRITERIA]=50107 AND [OPERATION]=11 AND [APPLICATION]=541 AND [ROOT_DOMAIN]=2109
DELETE FROM [synergix].[C_SUBSCRIBER_ALERT] WHERE [SUBSCRIBER_GROUP]=35 AND [CRITERIA]=50106 AND [OPERATION]=11 AND [APPLICATION]=541 AND [ROOT_DOMAIN]=2109
DELETE FROM [synergix].[C_SUBSCRIBER_ALERT] WHERE [SUBSCRIBER_GROUP]=34 AND [CRITERIA]=50105 AND [OPERATION]=11 AND [APPLICATION]=541 AND [ROOT_DOMAIN]=2109
DELETE FROM [synergix].[C_SUBSCRIBER_ALERT] WHERE [SUBSCRIBER_GROUP]=30 AND [CRITERIA]=50104 AND [OPERATION]=11 AND [APPLICATION]=541 AND [ROOT_DOMAIN]=2109
DELETE FROM [synergix].[C_ROLE_EXT] WHERE [ROLE_EXT]=2
DELETE FROM [synergix].[C_ROLE_EXT] WHERE [ROLE_EXT]=1




delete from  synergix.X_STATUS_NEXT_APPL where status_next = 3 and status !=3 
and application in (select application from synergix.A_APPLICATION where descend_application in (179))  --541

/*
ALTER TABLE ENERGY.C_REFERENCE CHECK  CONSTRAINT [R_SYNERGI_3927];
ALTER TABLE ENERGY.C_REFERENCE CHECK CONSTRAINT [R_SYNERGI_3928];
ALTER TABLE ENERGY.X_DOMAIN_APPL CHECK CONSTRAINT [R_SYNERGI_464];
ALTER TABLE ENERGY.X_DOMAIN CHECK CONSTRAINT [R_SYNERGI_463];
ALTER TABLE ENERGY.X_DOMAIN CHECK CONSTRAINT [R_SYNERGI_763];
ALTER TABLE ENERGY.C_CHECK_LIST_CATEGORY CHECK CONSTRAINT [R_SYNERGI_3909];
ALTER TABLE ENERGY.X_APPLICATION CHECK CONSTRAINT [R_SYNERGI_433];
ALTER TABLE ENERGY.C_CHECK_LIST CHECK CONSTRAINT [R_SYNERGI_1279];
ALTER TABLE ENERGY.X_CONNECTION_TYPE CHECK CONSTRAINT [R_SYNERGI_3844];
*/

    SET NOCOUNT OFF;
    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0
        ROLLBACK TRANSACTION;

    THROW; -- 오류 재전파
END CATCH

